---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  database_url: "{{ .Values.db.databaseUrl }}"
  database: {{ .Values.db.name }}
  table: {{ .Values.db.table }}
